import { User, Project, Task, Notification, ActivityLog, Comment, TimeEntry } from '@/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-admin-1',
    name: 'System Admin',
    email: 'admin@digitrench.com',
    password: 'admin123',
    role: 'admin',
    department: 'management',
    position: 'System Administrator',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    lastLogin: '2026-02-22T10:00:00Z',
  },
  {
    id: 'user-mgmt-1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@digitrench.com',
    password: 'mgmt123',
    role: 'management',
    department: 'management',
    position: 'Operations Manager',
    isActive: true,
    createdAt: '2024-01-15T00:00:00Z',
    lastLogin: '2026-02-22T09:00:00Z',
  },
  {
    id: 'user-mgmt-2',
    name: 'Michael Chen',
    email: 'michael.chen@digitrench.com',
    password: 'mgmt456',
    role: 'management',
    department: 'hr',
    position: 'HR Manager',
    isActive: true,
    createdAt: '2024-01-20T00:00:00Z',
    lastLogin: '2026-02-21T14:00:00Z',
  },
  {
    id: 'user-emp-1',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@digitrench.com',
    password: 'emp123',
    role: 'employee',
    department: 'hr',
    position: 'HR Specialist',
    isActive: true,
    createdAt: '2024-02-01T00:00:00Z',
    lastLogin: '2026-02-22T08:30:00Z',
  },
  {
    id: 'user-emp-2',
    name: 'James Wilson',
    email: 'james.wilson@digitrench.com',
    password: 'emp456',
    role: 'employee',
    department: 'call_center',
    position: 'Call Center Agent',
    isActive: true,
    createdAt: '2024-02-10T00:00:00Z',
    lastLogin: '2026-02-22T07:45:00Z',
  },
  {
    id: 'user-emp-3',
    name: 'Aisha Patel',
    email: 'aisha.patel@digitrench.com',
    password: 'emp789',
    role: 'employee',
    department: 'operations',
    position: 'Operations Analyst',
    isActive: true,
    createdAt: '2024-03-01T00:00:00Z',
    lastLogin: '2026-02-21T16:00:00Z',
  },
  {
    id: 'user-emp-4',
    name: 'David Kim',
    email: 'david.kim@digitrench.com',
    password: 'emp321',
    role: 'employee',
    department: 'finance',
    position: 'Finance Analyst',
    isActive: true,
    createdAt: '2024-03-15T00:00:00Z',
    lastLogin: '2026-02-20T11:00:00Z',
  },
  {
    id: 'user-emp-5',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@digitrench.com',
    password: 'emp654',
    role: 'employee',
    department: 'call_center',
    position: 'Senior Agent',
    isActive: true,
    createdAt: '2024-04-01T00:00:00Z',
    lastLogin: '2026-02-22T09:15:00Z',
  },
];

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Q1 HR Compliance Review',
    description: 'Quarterly HR compliance audit and documentation update for all departments',
    department: 'hr',
    createdBy: 'user-mgmt-2',
    members: ['user-emp-1', 'user-emp-4', 'user-mgmt-2'],
    status: 'active',
    startDate: '2026-01-01T00:00:00Z',
    endDate: '2026-03-31T00:00:00Z',
    color: '#6366f1',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-02-20T00:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'Call Center Performance Optimization',
    description: 'Improve call center KPIs and agent performance metrics for Q1',
    department: 'call_center',
    createdBy: 'user-mgmt-1',
    members: ['user-emp-2', 'user-emp-5', 'user-mgmt-1'],
    status: 'active',
    startDate: '2026-01-15T00:00:00Z',
    endDate: '2026-04-15T00:00:00Z',
    color: '#f59e0b',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-02-18T00:00:00Z',
  },
  {
    id: 'proj-3',
    name: 'Operations Process Streamlining',
    description: 'Document and optimize back-office operational workflows',
    department: 'operations',
    createdBy: 'user-mgmt-1',
    members: ['user-emp-3', 'user-mgmt-1'],
    status: 'active',
    startDate: '2026-02-01T00:00:00Z',
    endDate: '2026-05-01T00:00:00Z',
    color: '#10b981',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-22T00:00:00Z',
  },
  {
    id: 'proj-4',
    name: 'Employee Onboarding System',
    description: 'Create standardized onboarding process for new hires',
    department: 'hr',
    createdBy: 'user-mgmt-2',
    members: ['user-emp-1', 'user-mgmt-2'],
    status: 'active',
    startDate: '2026-02-10T00:00:00Z',
    endDate: '2026-04-10T00:00:00Z',
    color: '#ec4899',
    createdAt: '2026-02-10T00:00:00Z',
    updatedAt: '2026-02-21T00:00:00Z',
  },
  {
    id: 'proj-5',
    name: 'Finance Reporting Automation',
    description: 'Automate monthly financial reports and dashboards',
    department: 'finance',
    createdBy: 'user-mgmt-1',
    members: ['user-emp-4', 'user-mgmt-1'],
    status: 'on_hold',
    startDate: '2026-03-01T00:00:00Z',
    endDate: '2026-06-01T00:00:00Z',
    color: '#3b82f6',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Update Employee Handbook 2026',
    description: 'Review and update the employee handbook with new policies, benefits information, and compliance requirements for 2026.',
    projectId: 'proj-1',
    assigneeId: 'user-emp-1',
    createdBy: 'user-mgmt-2',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2026-02-28T00:00:00Z',
    startDate: '2026-02-10T00:00:00Z',
    tags: ['documentation', 'compliance', 'hr'],
    attachments: [],
    comments: [
      {
        id: 'comment-1',
        taskId: 'task-1',
        userId: 'user-mgmt-2',
        content: 'Please make sure to include the new remote work policy in section 4. @emily.rodriguez',
        mentions: ['user-emp-1'],
        attachments: [],
        createdAt: '2026-02-15T10:00:00Z',
        updatedAt: '2026-02-15T10:00:00Z',
      },
      {
        id: 'comment-2',
        taskId: 'task-1',
        userId: 'user-emp-1',
        content: 'Understood! I\'ve started working on section 4. Will have a draft ready by Friday.',
        mentions: [],
        attachments: [],
        createdAt: '2026-02-15T11:30:00Z',
        updatedAt: '2026-02-15T11:30:00Z',
      },
    ],
    subtasks: [
      { id: 'sub-1', title: 'Review current handbook', completed: true },
      { id: 'sub-2', title: 'Draft new remote work policy', completed: true },
      { id: 'sub-3', title: 'Update benefits section', completed: false },
      { id: 'sub-4', title: 'Legal review', completed: false },
    ],
    timeEntries: [
      {
        id: 'te-1',
        taskId: 'task-1',
        userId: 'user-emp-1',
        startTime: '2026-02-20T09:00:00Z',
        endTime: '2026-02-20T12:00:00Z',
        duration: 180,
        notes: 'Reviewed current handbook and drafted new sections',
        date: '2026-02-20',
      },
    ],
    estimatedHours: 16,
    actualHours: 3,
    createdAt: '2026-02-10T00:00:00Z',
    updatedAt: '2026-02-20T12:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Conduct Q1 Performance Reviews',
    description: 'Schedule and conduct performance review meetings with all HR department employees for Q1 2026.',
    projectId: 'proj-1',
    assigneeId: 'user-emp-1',
    createdBy: 'user-mgmt-2',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-03-15T00:00:00Z',
    tags: ['performance', 'hr', 'reviews'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 'sub-5', title: 'Prepare review templates', completed: false },
      { id: 'sub-6', title: 'Schedule meetings', completed: false },
      { id: 'sub-7', title: 'Conduct reviews', completed: false },
      { id: 'sub-8', title: 'Document outcomes', completed: false },
    ],
    timeEntries: [],
    estimatedHours: 24,
    actualHours: 0,
    createdAt: '2026-02-12T00:00:00Z',
    updatedAt: '2026-02-12T00:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Improve Average Handle Time (AHT)',
    description: 'Analyze current call patterns and implement strategies to reduce average handle time by 15% while maintaining quality scores.',
    projectId: 'proj-2',
    assigneeId: 'user-emp-2',
    createdBy: 'user-mgmt-1',
    status: 'in_progress',
    priority: 'urgent',
    dueDate: '2026-02-25T00:00:00Z',
    startDate: '2026-02-01T00:00:00Z',
    tags: ['kpi', 'call-center', 'performance'],
    attachments: [],
    comments: [
      {
        id: 'comment-3',
        taskId: 'task-3',
        userId: 'user-mgmt-1',
        content: 'This is critical for our Q1 targets. Please provide daily updates. @james.wilson',
        mentions: ['user-emp-2'],
        attachments: [],
        createdAt: '2026-02-10T09:00:00Z',
        updatedAt: '2026-02-10T09:00:00Z',
      },
    ],
    subtasks: [
      { id: 'sub-9', title: 'Analyze call recordings', completed: true },
      { id: 'sub-10', title: 'Identify bottlenecks', completed: true },
      { id: 'sub-11', title: 'Implement new call scripts', completed: false },
      { id: 'sub-12', title: 'Measure improvement', completed: false },
    ],
    timeEntries: [
      {
        id: 'te-2',
        taskId: 'task-3',
        userId: 'user-emp-2',
        startTime: '2026-02-20T08:00:00Z',
        endTime: '2026-02-20T17:00:00Z',
        duration: 480,
        notes: 'Analyzed 50 call recordings and identified key patterns',
        date: '2026-02-20',
      },
    ],
    estimatedHours: 40,
    actualHours: 8,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-20T17:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Customer Satisfaction Survey Analysis',
    description: 'Compile and analyze Q4 2025 customer satisfaction survey results and prepare presentation for management.',
    projectId: 'proj-2',
    assigneeId: 'user-emp-5',
    createdBy: 'user-mgmt-1',
    status: 'review',
    priority: 'high',
    dueDate: '2026-02-23T00:00:00Z',
    startDate: '2026-02-15T00:00:00Z',
    tags: ['analysis', 'customer-satisfaction', 'reporting'],
    attachments: [
      {
        id: 'att-1',
        name: 'CSAT_Analysis_Draft.pdf',
        url: '/attachments/csat-analysis.pdf',
        type: 'application/pdf',
        size: 2048000,
        uploadedBy: 'user-emp-5',
        uploadedAt: '2026-02-21T14:00:00Z',
      },
    ],
    comments: [
      {
        id: 'comment-4',
        taskId: 'task-4',
        userId: 'user-emp-5',
        content: 'Analysis complete. Uploaded draft for review. Key finding: 87% satisfaction rate, up from 82% in Q3.',
        mentions: [],
        attachments: [],
        createdAt: '2026-02-21T14:30:00Z',
        updatedAt: '2026-02-21T14:30:00Z',
      },
    ],
    subtasks: [
      { id: 'sub-13', title: 'Collect survey data', completed: true },
      { id: 'sub-14', title: 'Data analysis', completed: true },
      { id: 'sub-15', title: 'Create presentation', completed: true },
      { id: 'sub-16', title: 'Management review', completed: false },
    ],
    timeEntries: [
      {
        id: 'te-3',
        taskId: 'task-4',
        userId: 'user-emp-5',
        startTime: '2026-02-19T09:00:00Z',
        endTime: '2026-02-19T17:00:00Z',
        duration: 480,
        notes: 'Data collection and initial analysis',
        date: '2026-02-19',
      },
      {
        id: 'te-4',
        taskId: 'task-4',
        userId: 'user-emp-5',
        startTime: '2026-02-21T09:00:00Z',
        endTime: '2026-02-21T14:00:00Z',
        duration: 300,
        notes: 'Created presentation and uploaded draft',
        date: '2026-02-21',
      },
    ],
    estimatedHours: 20,
    actualHours: 13,
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-02-21T14:30:00Z',
  },
  {
    id: 'task-5',
    title: 'Document Back-Office Workflows',
    description: 'Create comprehensive documentation for all back-office operational processes including data entry, quality checks, and escalation procedures.',
    projectId: 'proj-3',
    assigneeId: 'user-emp-3',
    createdBy: 'user-mgmt-1',
    status: 'in_progress',
    priority: 'medium',
    dueDate: '2026-03-10T00:00:00Z',
    startDate: '2026-02-05T00:00:00Z',
    tags: ['documentation', 'operations', 'process'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 'sub-17', title: 'Map current workflows', completed: true },
      { id: 'sub-18', title: 'Interview team leads', completed: true },
      { id: 'sub-19', title: 'Draft documentation', completed: false },
      { id: 'sub-20', title: 'Review and finalize', completed: false },
    ],
    timeEntries: [
      {
        id: 'te-5',
        taskId: 'task-5',
        userId: 'user-emp-3',
        startTime: '2026-02-18T09:00:00Z',
        endTime: '2026-02-18T16:00:00Z',
        duration: 420,
        notes: 'Mapped 5 core workflows',
        date: '2026-02-18',
      },
    ],
    estimatedHours: 32,
    actualHours: 7,
    createdAt: '2026-02-05T00:00:00Z',
    updatedAt: '2026-02-18T16:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Create Onboarding Checklist',
    description: 'Develop a comprehensive onboarding checklist for new employees covering IT setup, HR documentation, training schedule, and department orientation.',
    projectId: 'proj-4',
    assigneeId: 'user-emp-1',
    createdBy: 'user-mgmt-2',
    status: 'done',
    priority: 'high',
    dueDate: '2026-02-20T00:00:00Z',
    startDate: '2026-02-10T00:00:00Z',
    completedAt: '2026-02-19T15:00:00Z',
    tags: ['onboarding', 'hr', 'documentation'],
    attachments: [
      {
        id: 'att-2',
        name: 'Onboarding_Checklist_v1.docx',
        url: '/attachments/onboarding-checklist.docx',
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        size: 512000,
        uploadedBy: 'user-emp-1',
        uploadedAt: '2026-02-19T15:00:00Z',
      },
    ],
    comments: [
      {
        id: 'comment-5',
        taskId: 'task-6',
        userId: 'user-mgmt-2',
        content: 'Excellent work! This checklist is comprehensive and well-organized. Approved!',
        mentions: [],
        attachments: [],
        createdAt: '2026-02-20T09:00:00Z',
        updatedAt: '2026-02-20T09:00:00Z',
      },
    ],
    subtasks: [
      { id: 'sub-21', title: 'IT setup checklist', completed: true },
      { id: 'sub-22', title: 'HR documentation list', completed: true },
      { id: 'sub-23', title: 'Training schedule template', completed: true },
      { id: 'sub-24', title: 'Department orientation guide', completed: true },
    ],
    timeEntries: [
      {
        id: 'te-6',
        taskId: 'task-6',
        userId: 'user-emp-1',
        startTime: '2026-02-17T09:00:00Z',
        endTime: '2026-02-17T17:00:00Z',
        duration: 480,
        notes: 'Created initial draft',
        date: '2026-02-17',
      },
      {
        id: 'te-7',
        taskId: 'task-6',
        userId: 'user-emp-1',
        startTime: '2026-02-19T09:00:00Z',
        endTime: '2026-02-19T15:00:00Z',
        duration: 360,
        notes: 'Finalized and uploaded',
        date: '2026-02-19',
      },
    ],
    estimatedHours: 16,
    actualHours: 14,
    createdAt: '2026-02-10T00:00:00Z',
    updatedAt: '2026-02-19T15:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Monthly Financial Report - January 2026',
    description: 'Compile and prepare the monthly financial report for January 2026 including revenue, expenses, and variance analysis.',
    projectId: 'proj-5',
    assigneeId: 'user-emp-4',
    createdBy: 'user-mgmt-1',
    status: 'blocked',
    priority: 'urgent',
    dueDate: '2026-02-15T00:00:00Z',
    startDate: '2026-02-01T00:00:00Z',
    tags: ['finance', 'reporting', 'monthly'],
    attachments: [],
    comments: [
      {
        id: 'comment-6',
        taskId: 'task-7',
        userId: 'user-emp-4',
        content: 'Blocked waiting for data from accounting system. @sarah.johnson can you help escalate?',
        mentions: ['user-mgmt-1'],
        attachments: [],
        createdAt: '2026-02-14T10:00:00Z',
        updatedAt: '2026-02-14T10:00:00Z',
      },
    ],
    subtasks: [
      { id: 'sub-25', title: 'Collect financial data', completed: false },
      { id: 'sub-26', title: 'Variance analysis', completed: false },
      { id: 'sub-27', title: 'Prepare report', completed: false },
      { id: 'sub-28', title: 'Management review', completed: false },
    ],
    timeEntries: [],
    estimatedHours: 12,
    actualHours: 0,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-14T10:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Agent Training Program - New Scripts',
    description: 'Develop and deliver training program for new call scripts to all call center agents.',
    projectId: 'proj-2',
    assigneeId: 'user-emp-5',
    createdBy: 'user-mgmt-1',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-03-01T00:00:00Z',
    tags: ['training', 'call-center', 'scripts'],
    attachments: [],
    comments: [],
    subtasks: [
      { id: 'sub-29', title: 'Develop training materials', completed: false },
      { id: 'sub-30', title: 'Schedule training sessions', completed: false },
      { id: 'sub-31', title: 'Conduct training', completed: false },
      { id: 'sub-32', title: 'Assessment and feedback', completed: false },
    ],
    timeEntries: [],
    estimatedHours: 20,
    actualHours: 0,
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-emp-1',
    type: 'task_assigned',
    title: 'New Task Assigned',
    message: 'You have been assigned "Update Employee Handbook 2026"',
    taskId: 'task-1',
    projectId: 'proj-1',
    fromUserId: 'user-mgmt-2',
    isRead: false,
    createdAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-emp-1',
    type: 'comment_mention',
    title: 'You were mentioned',
    message: 'Michael Chen mentioned you in a comment on "Update Employee Handbook 2026"',
    taskId: 'task-1',
    fromUserId: 'user-mgmt-2',
    isRead: false,
    createdAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-emp-2',
    type: 'deadline_reminder',
    title: 'Deadline Approaching',
    message: '"Improve Average Handle Time" is due in 3 days',
    taskId: 'task-3',
    isRead: false,
    createdAt: '2026-02-22T08:00:00Z',
  },
  {
    id: 'notif-4',
    userId: 'user-mgmt-1',
    type: 'review_request',
    title: 'Task Ready for Review',
    message: 'Lisa Thompson marked "Customer Satisfaction Survey Analysis" as ready for review',
    taskId: 'task-4',
    fromUserId: 'user-emp-5',
    isRead: false,
    createdAt: '2026-02-21T14:30:00Z',
  },
  {
    id: 'notif-5',
    userId: 'user-mgmt-1',
    type: 'status_change',
    title: 'Task Status Updated',
    message: 'Emily Rodriguez updated "Create Onboarding Checklist" to Done',
    taskId: 'task-6',
    fromUserId: 'user-emp-1',
    isRead: true,
    createdAt: '2026-02-19T15:00:00Z',
  },
  {
    id: 'notif-6',
    userId: 'user-emp-5',
    type: 'task_assigned',
    title: 'New Task Assigned',
    message: 'You have been assigned "Agent Training Program - New Scripts"',
    taskId: 'task-8',
    fromUserId: 'user-mgmt-1',
    isRead: false,
    createdAt: '2026-02-15T00:00:00Z',
  },
];

// Mock Activity Logs
export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log-1',
    userId: 'user-emp-1',
    action: 'Updated task status to In Progress',
    entityType: 'task',
    entityId: 'task-1',
    details: { from: 'todo', to: 'in_progress' },
    createdAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'log-2',
    userId: 'user-emp-5',
    action: 'Uploaded attachment to task',
    entityType: 'task',
    entityId: 'task-4',
    details: { fileName: 'CSAT_Analysis_Draft.pdf' },
    createdAt: '2026-02-21T14:00:00Z',
  },
  {
    id: 'log-3',
    userId: 'user-emp-1',
    action: 'Completed task',
    entityType: 'task',
    entityId: 'task-6',
    details: { status: 'done' },
    createdAt: '2026-02-19T15:00:00Z',
  },
  {
    id: 'log-4',
    userId: 'user-mgmt-2',
    action: 'Created new project',
    entityType: 'project',
    entityId: 'proj-4',
    details: { projectName: 'Employee Onboarding System' },
    createdAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'log-5',
    userId: 'user-emp-2',
    action: 'Logged 8 hours on task',
    entityType: 'task',
    entityId: 'task-3',
    details: { hours: 8 },
    createdAt: '2026-02-20T17:00:00Z',
  },
];

export const getInitialData = () => ({
  users: mockUsers,
  projects: mockProjects,
  tasks: mockTasks,
  notifications: mockNotifications,
  activityLogs: mockActivityLogs,
});
